name: Build Subtitles

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      - 'README.md'

env:
      PYTHONUNBUFFERED: "1"

jobs:
  Build-CI-Versions:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --user git+https://github.com/FichteForks/Myaamori-Aegisub-Scripts.git@pr/fix-style-deduplication#subdirectory=scripts/sub-digest
          pip install requests
      - name: Install custom fonts
        shell: pwsh
        run: |
          $fontSourceFolder = "Fonts\"
          $SystemFontsPath = "C:\Windows\Fonts\"
          
          foreach($FontFile in Get-ChildItem $fontSourceFolder -Include '*.ttf','*.ttc','*.otf' -recurse ) {
            $targetPath = Join-Path $SystemFontsPath $FontFile.Name
          
              if(![System.IO.Path]::IsPathRooted($fontSourceFolder)){
                  $fontSourceFolder = $FontFile.Directory.FullName
              }
            if(Test-Path -Path $targetPath){
              $FontFile.Name + " already installed"
            }
            else {
              "Installing font " + $FontFile.Name
              
              #Extract Font information for Reqistry 
              $ShellFolder = (New-Object -COMObject Shell.Application).Namespace($fontSourceFolder)
              $ShellFile = $ShellFolder.ParseName($FontFile.name)
              $ShellFileType = $ShellFolder.GetDetailsOf($ShellFile, 2)
          
              #Set the $FontType Variable
              If ($ShellFileType -Like '*TrueType font file*') {$FontType = '(TrueType)'}
                
              #Update Registry and copy font to font directory
              $RegName = $ShellFolder.GetDetailsOf($ShellFile, 21) + ' ' + $FontType
              $null = New-ItemProperty -Name $RegName -Path "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Fonts" -PropertyType string -Value $FontFile.name -Force
              Copy-item $FontFile.FullName -Destination $SystemFontsPath
              "Done"
            }
          }
      - name: Build substitles
        run: |
          python build.py
      - name: Pack files
        shell: pwsh
        run: |
            $now = Get-Date -Format "yyyyMMddHHmm"
            Compress-Archive -Path build\output\* -DestinationPath "mlan_subs_${now}.zip"
      - name: Delete latest release
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo } = context.repo
            const response = await github.rest.repos.getReleaseByTag({ owner, repo, tag:'latest' } )
            const releaseid = response.data.id
            if (!releaseid) {return}
            await github.rest.repos.deleteRelease({ owner, repo, "release_id": releaseid })
            await github.rest.git.deleteRef({ owner, repo, ref: 'tags/latest' })
      - name: Publish
        uses: "softprops/action-gh-release@v1"
        with:
          tag_name: "latest"
          fail_on_unmatched_files: true
          prerelease: true
          draft: false
          generate_release_notes: true
          name: "自动生成构建 Automatic CI Build"
          files: |
            mlan_subs_*.zip